import assert from "node:assert/strict";
import { execFile as execFileCb } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { promisify } from "node:util";
import { commitLocalChanges, ensureIgnoreRules, isDenied, readConfig, runInit, runLink, runSync, shouldAutoSync, stagedSecretFiles, stripJsonComments, withLock, type GhClient } from "../extensions/git-sync.ts";

process.env.GIT_AUTHOR_NAME = process.env.GIT_COMMITTER_NAME = "pi-git-sync tests";
process.env.GIT_AUTHOR_EMAIL = process.env.GIT_COMMITTER_EMAIL = "tests@pi-git-sync.invalid";
process.env.GIT_CONFIG_GLOBAL = os.devNull;
process.env.GIT_CONFIG_SYSTEM = os.devNull;

const exec = promisify(execFileCb);
const ctx = { hasUI: false, ui: { setStatus() {}, notify() {} } } as never;
async function sh(cmd: string, args: string[], cwd?: string) { return exec(cmd, args, { cwd }); }
async function machine(name: string) { const root = await fs.mkdtemp(path.join(os.tmpdir(), `pi-git-sync-${name}-`)); const dir = path.join(root, "agent"); await fs.mkdir(path.join(dir, "extensions"), { recursive: true }); await fs.writeFile(path.join(dir, "settings.json"), JSON.stringify({ machine: name })); await fs.writeFile(path.join(dir, "AGENTS.md"), "rules\n"); await fs.writeFile(path.join(dir, "extensions", "foo.ts"), "export {}\n"); await fs.writeFile(path.join(dir, "auth.json"), `secret-${name}`); return { root, dir }; }
async function bare(root: string, name = "origin.git") { const repo = path.join(root, name); await sh("git", ["init", "--bare", repo]); return repo; }
function fakeGh(overrides: Partial<GhClient> = {}): GhClient & { calls: string[] } { const calls: string[] = []; return { calls, async available() { calls.push("available"); return true; }, async currentUser() { calls.push("user"); return "tester"; }, async repoExists(id: string) { calls.push(`exists:${id}`); return false; }, async isPrivate(id: string) { calls.push(`private:${id}`); return true; }, async createPrivateRepo(id: string) { calls.push(`create:${id}`); }, remoteUrl(id: string) { return `https://github.com/${id}.git`; }, ...overrides }; }

test("init, link, and sync round-trip without network", async () => { const a = await machine("a"), remote = await bare(a.root); await runInit(remote, ctx, { dir: a.dir, gh: fakeGh() }); const b = await machine("b"); await fs.writeFile(path.join(b.dir, "settings.json"), '{"machine":"local"}'); await runLink(remote, ctx, { dir: b.dir, gh: fakeGh() }); assert.equal(await fs.readFile(path.join(b.dir, "auth.json"), "utf8"), "secret-b"); assert.equal(await fs.readFile(path.join(b.dir, "settings.json"), "utf8"), '{"machine":"a"}'); assert.equal(await fs.readFile(path.join(b.dir, "settings.json.local-backup"), "utf8"), '{"machine":"local"}'); await fs.writeFile(path.join(b.dir, "settings.json"), '{"machine":"updated"}'); await runSync(ctx, { auto: false, push: true }, { dir: b.dir, gh: fakeGh() }); await runSync(ctx, { auto: false, push: true }, { dir: a.dir, gh: fakeGh() }); assert.equal(await fs.readFile(path.join(a.dir, "settings.json"), "utf8"), '{"machine":"updated"}'); });

test("staging guard refuses secrets even when manually force-added", async () => { const a = await machine("guard"); await sh("git", ["init", "-b", "main"], a.dir); await ensureIgnoreRules(a.dir); await fs.mkdir(path.join(a.dir, "extensions", "secrets"), { recursive: true }); await fs.writeFile(path.join(a.dir, "extensions", "secrets", "api-keys.json"), "k"); await sh("git", ["add", "-f", "auth.json", "extensions/foo.ts", "extensions/secrets/api-keys.json"], a.dir); await assert.rejects(() => commitLocalChanges({ dir: a.dir }), /sensitive paths: .*auth\.json.*extensions\/secrets\/api-keys\.json/s); assert.deepEqual(await stagedSecretFiles(a.dir), []); });

test("denylist matches every path segment and ignore-pattern class", () => { for (const file of ["secrets/key.json", "tokens/x.txt", "auth/x.json", "extensions/secrets/api-keys.json", "prod.env", "foo.local.json", "sub/creds.env.bak", ".env", "a/.env.production", "state/x", "npm/pkg/index.js"]) assert.ok(isDenied(file), `expected denied: ${file}`); for (const file of ["settings.json", "AGENTS.md", "extensions/foo.ts", "chains/build.chain.md", "themes/t.json", "git-sync.jsonc"]) assert.ok(!isDenied(file), `expected allowed: ${file}`); });

test("sync refuses a parent repo when the agent dir is not a repo", async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), "pi-git-sync-parent-")); await sh("git", ["init", "-b", "main"], root); const remote = await bare(root, "home-origin.git"); await sh("git", ["remote", "add", "origin", remote], root); await fs.writeFile(path.join(root, "private-note.txt"), "home file"); const dir = path.join(root, "agent"); await fs.mkdir(dir, { recursive: true }); assert.equal(await shouldAutoSync({ dir }), false); let warned = ""; await runSync(ctx, { auto: false, push: true }, { dir, gh: fakeGh(), notify: text => { warned = text; } }); assert.match(warned, /no git repo/); const { stdout } = await sh("git", ["status", "--porcelain"], root); assert.match(stdout, /private-note\.txt/); const log = await sh("git", ["log", "--oneline"], root).catch(() => ({ stdout: "" })); assert.doesNotMatch(log.stdout, /auto-sync/); });

test("init writes an allowlist before its first commit", async () => { const a = await machine("rules"), remote = await bare(a.root); await runInit(remote, ctx, { dir: a.dir, gh: fakeGh() }); const tree = (await sh("git", ["ls-tree", "-r", "--name-only", "HEAD"], a.dir)).stdout.split("\n"); assert(tree.includes(".gitignore")); assert(!tree.some(x => x === "auth.json")); assert.match(await fs.readFile(path.join(a.dir, ".git", "info", "exclude"), "utf8"), /auth\*/); });

test("init aborts when secrets are already tracked", async () => { const a = await machine("tracked"), remote = await bare(a.root); await sh("git", ["init", "-b", "main"], a.dir); await sh("git", ["add", "-f", "auth.json"], a.dir); await sh("git", ["commit", "-m", "oops"], a.dir); await assert.rejects(() => runInit(remote, ctx, { dir: a.dir, gh: fakeGh() }), /tracked sensitive files: auth\.json/); });

test("init without a URL creates a private repo through gh", async () => { const a = await machine("gh-init"); const repo = await bare(a.root, "created.git"); const gh = fakeGh({ remoteUrl: () => repo }); await runInit("", ctx, { dir: a.dir, gh }); assert.ok(gh.calls.includes("create:tester/pi-agent-config"), gh.calls.join(",")); const heads = (await sh("git", ["ls-remote", "--heads", repo])).stdout; assert.match(heads, /refs\/heads\/main/); });

test("init suggests link when the repo already exists on gh", async () => { const a = await machine("gh-exists"); const gh = fakeGh({ repoExists: async () => true }); await assert.rejects(() => runInit("", ctx, { dir: a.dir, gh }), /use \/gitsync link/); });

test("init rejects an invalid repository reference", async () => { const a = await machine("gh-bad"); await assert.rejects(() => runInit("a/b/c", ctx, { dir: a.dir, gh: fakeGh() }), /invalid repository reference/); });

test("link discovers an existing sync repo through gh", async () => { const a = await machine("seed"), remote = await bare(a.root); await runInit(remote, ctx, { dir: a.dir, gh: fakeGh() }); const b = await machine("linked"); const gh = fakeGh({ repoExists: async id => id === "tester/pi-config", remoteUrl: () => remote }); await runLink("", ctx, { dir: b.dir, gh }); assert.equal((await sh("git", ["remote", "get-url", "origin"], b.dir)).stdout.trim(), remote); assert.equal(await fs.readFile(path.join(b.dir, "settings.json"), "utf8"), '{"machine":"seed"}'); });

test("link refuses to overwrite existing local git history", async () => { const a = await machine("seed2"), remote = await bare(a.root); await runInit(remote, ctx, { dir: a.dir, gh: fakeGh() }); const b = await machine("history"); await sh("git", ["init", "-b", "main"], b.dir); await sh("git", ["add", "extensions/foo.ts"], b.dir); await sh("git", ["commit", "-m", "local work"], b.dir); await assert.rejects(() => runLink(remote, ctx, { dir: b.dir, gh: fakeGh() }), /existing git history/); assert.equal(await fs.readFile(path.join(b.dir, "extensions", "foo.ts"), "utf8"), "export {}\n"); });

test("legacy pi-git-sync managed block is migrated, custom rules kept", async () => { const a = await machine("legacy"); const legacy = "# >>> pi-git-sync managed — do not edit inside this block\n*\n!settings.json\nauth*\n# <<< pi-git-sync managed\n"; await fs.writeFile(path.join(a.dir, ".gitignore"), `custom-rule\n${legacy}`); await ensureIgnoreRules(a.dir); const ignore = await fs.readFile(path.join(a.dir, ".gitignore"), "utf8"); assert.doesNotMatch(ignore, /pi-git-sync managed/); assert.match(ignore, /pi-config-sync managed/); assert.match(ignore, /custom-rule/); assert.equal(ignore.match(/managed — do not edit/g)?.length, 1); });

test("lock skips a live owner, clears a dead owner, and ignores corrupt pids", async () => { const a = await machine("lock"), state = path.join(a.dir, ".git-sync"); await fs.mkdir(state); await fs.writeFile(path.join(state, "lock"), JSON.stringify({ pid: process.pid, startedAt: new Date().toISOString() })); assert.equal(await withLock(ctx, async () => "ran", { dir: a.dir }), undefined); await fs.writeFile(path.join(state, "lock"), JSON.stringify({ pid: 999999, startedAt: new Date(0).toISOString() })); assert.equal(await withLock(ctx, async () => "ran", { dir: a.dir }), "ran"); await fs.writeFile(path.join(state, "lock"), JSON.stringify({ pid: 0, startedAt: new Date().toISOString() })); assert.equal(await withLock(ctx, async () => "ran2", { dir: a.dir }), "ran2"); await assert.rejects(fs.access(path.join(state, "lock"))); });

test("JSONC config drives rate limit, hostname, warnings, and extra paths", async () => { const a = await machine("config"); await sh("git", ["init", "-b", "main"], a.dir); await sh("git", ["remote", "add", "origin", path.join(a.root, "none")], a.dir); await fs.writeFile(path.join(a.dir, "git-sync.jsonc"), '{ /* comment */ "autoSyncIntervalMinutes": 30, "includeHostname": false, "extraPaths": ["safe", "notes/safe", "my.dir/", "../bad", "mytoken"] }'); await fs.mkdir(path.join(a.dir, ".git-sync")); await fs.writeFile(path.join(a.dir, ".git-sync", "state.json"), JSON.stringify({ lastAutoSyncAt: new Date().toISOString() })); assert.equal(stripJsonComments('{// x\n"a": 1}'), '{\n"a": 1}'); assert.equal(await shouldAutoSync({ dir: a.dir }), false); await fs.writeFile(path.join(a.dir, ".git-sync", "state.json"), JSON.stringify({ lastAutoSyncAt: new Date(Date.now() - 31 * 60_000).toISOString() })); assert.equal(await shouldAutoSync({ dir: a.dir }), true); let warning = ""; const config = await readConfig({ dir: a.dir, notify: text => { warning = text; } }); assert.match(warning, /unsafe extraPaths/); await ensureIgnoreRules(a.dir, config); const ignore = await fs.readFile(path.join(a.dir, ".gitignore"), "utf8"); assert.match(ignore, /!safe\//); assert.match(ignore, /!notes\/\n/); assert.match(ignore, /!notes\/safe\/\*\*/); assert.match(ignore, /!my\.dir\/\*\*/); assert.doesNotMatch(ignore, /mytoken/); await fs.mkdir(path.join(a.dir, "notes"), { recursive: true }); await fs.writeFile(path.join(a.dir, "notes", "safe"), "n\n"); await fs.mkdir(path.join(a.dir, "my.dir"), { recursive: true }); await fs.writeFile(path.join(a.dir, "my.dir", "inner.md"), "m\n"); for (const tracked of ["notes/safe", "my.dir/inner.md"]) { const ignored = await sh("git", ["check-ignore", tracked], a.dir).then(() => true).catch(() => false); assert.equal(ignored, false, `expected synced: ${tracked}`); } await commitLocalChanges({ dir: a.dir }); assert.equal((await sh("git", ["log", "-1", "--format=%s"], a.dir)).stdout.trim(), "pi config: auto-sync"); });
