import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import type { ExtensionAPI, ExtensionCommandContext, ExtensionContext } from "@earendil-works/pi-coding-agent";

const exec = promisify(execFile);
const STATUS_KEY = "git-sync";
const START = "# >>> pi-git-sync managed — do not edit inside this block";
const END = "# <<< pi-git-sync managed";
const DEFAULT_PATHS = [".gitignore", "settings.json", "AGENTS.md", "git-sync.jsonc", "extensions", "chains", "prompts", "themes", "skills"];
const IGNORE_DENY = ["auth*", "*token*", "*secret*", "*credential*", "*.env", "*.env.*", "*.local.json", "**/node_modules/", ".DS_Store"];
const LIKELY_SYNC_REPO_NAMES = ["pi-agent-config", "my-pi-config", "pi-config", "pi-git-sync-config", "dotfiles-pi"];

export interface GitSyncConfig { autoSyncIntervalMinutes?: number; includeHostname?: boolean; extraPaths?: string[]; warnOnPublicRemote?: boolean }
export interface GhClient { available(): Promise<boolean>; currentUser(): Promise<string>; repoExists(id: string): Promise<boolean>; isPrivate(id: string): Promise<boolean | undefined>; createPrivateRepo(id: string): Promise<void>; remoteUrl(id: string): string }
export interface Deps { dir?: string; gh?: GhClient; notify?: (message: string, level: Level) => void }
type Level = "info" | "warning" | "error";
type Ctx = ExtensionContext | ExtensionCommandContext;

export default function gitSync(pi: ExtensionAPI) {
	pi.registerCommand("gitsync", { description: "Securely sync pi config (init, link, status, sync, push, pull)", getArgumentCompletions: prefix => {
		const entries = ["init", "link", "status", "sync", "push", "pull"].map(value => ({ value, label: value })).filter(x => x.value.startsWith(prefix.trim()));
		return entries.length ? entries : null;
	}, handler: async (args, ctx) => {
		const [command = "status", ...rest] = args.trim().split(/\s+/); const arg = rest.join(" ");
		try { await withLock(ctx, async () => {
			if (command === "init") return runInit(arg, ctx);
			if (command === "link") return runLink(arg, ctx);
			if (command === "status") return showStatus(ctx);
			if (command === "sync") return runSync(ctx, { auto: false, push: true });
			if (command === "push") return runSync(ctx, { auto: false, push: true, skipPull: true });
			if (command === "pull") return runSync(ctx, { auto: false, push: false });
			throw new Error("Unknown command. Usage: /gitsync [init|link|status|sync|push|pull]");
		}); } catch (error) { notify(ctx, `git-sync: ${message(error)}`, "error"); }
	} });
	pi.on("session_start", async (_event, ctx) => { if (await shouldAutoSync()) try { await withLock(ctx, async () => { await writeState({ lastAutoSyncAt: new Date().toISOString() }); await runSync(ctx, { auto: true, push: true }); }); } catch (error) { notify(ctx, `git-sync skipped: ${message(error)}`, "warning"); } });
	pi.on("session_shutdown", async (event, ctx) => { const reason = typeof event === "object" && event ? (event as { reason?: string }).reason : undefined; if (reason === "reload" || isSubagentChild() || !(await isSyncableRepo())) return; try { await withLock(ctx, async () => { await prepareCommit(undefined, ctx); await commitLocalChanges(undefined, undefined, ctx); await bestEffortPush(); }); } catch {} });
}

function dirOf(deps?: Deps) { const value = deps?.dir ?? process.env.PI_CODING_AGENT_DIR?.trim(); return !value ? path.join(os.homedir(), ".pi", "agent") : value === "~" || value.startsWith("~/") ? path.join(os.homedir(), value.slice(2)) : path.resolve(value); }
function gitEnv(dir: string) { return { ...process.env, GIT_TERMINAL_PROMPT: "0", GIT_CEILING_DIRECTORIES: path.dirname(dir) }; }
function git(args: string[], dir: string, timeout = 10_000) { return exec("git", args, { cwd: dir, timeout, maxBuffer: 16 * 1024 * 1024, env: gitEnv(dir) }); }
function gitRaw(args: string[], dir: string) { return exec("git", args, { cwd: dir, timeout: 10_000, maxBuffer: 64 * 1024 * 1024, encoding: "buffer", env: gitEnv(dir) }) as unknown as Promise<{ stdout: Buffer; stderr: Buffer }>; }
function notify(ctx: Ctx | undefined, text: string, level: Level, deps?: Deps) { if (deps?.notify) deps.notify(text, level); else if (ctx?.hasUI) ctx.ui.notify(text, level); }
const warnedOnce = new Set<string>();
function warnOnce(ctx: Ctx | undefined, text: string, deps: Deps | undefined, key = text) { if (warnedOnce.has(key) || !(deps?.notify || ctx?.hasUI)) return; warnedOnce.add(key); notify(ctx, text, "warning", deps); }
function message(error: unknown) { return error instanceof Error ? error.message : String(error); }
function stateDir(dir: string) { return path.join(dir, ".git-sync"); }
function statePath(dir: string) { return path.join(stateDir(dir), "state.json"); }
function lockPath(dir: string) { return path.join(stateDir(dir), "lock"); }
function isSubagentChild() { return Number(process.env.PI_SUBAGENT_DEPTH ?? "0") > 0; }

export function isDenied(file: string) { const parts = file.toLowerCase().replaceAll("\\", "/").split("/").filter(Boolean); return parts.some(part => ["sessions", "state", "npm", "git", "bin", ".git-sync", "node_modules"].includes(part) || part.startsWith("auth") || part.includes("token") || part.includes("secret") || part.includes("credential") || part === ".env" || part.includes(".env.") || part.endsWith(".env") || part.endsWith(".local.json")); }
function validExtra(entry: string) { return entry.trim() !== "" && !entry.includes("..") && !path.isAbsolute(entry) && !isDenied(entry); }
export function stripJsonComments(input: string) { let out = "", quote = "", escaped = false; for (let i = 0; i < input.length; i++) { const c = input[i]!, next = input[i + 1]; if (quote) { out += c; if (escaped) escaped = false; else if (c === "\\") escaped = true; else if (c === quote) quote = ""; continue; } if (c === '"' || c === "'") { quote = c; out += c; } else if (c === "/" && next === "/") { while (i < input.length && input[i] !== "\n") i++; out += "\n"; } else if (c === "/" && next === "*") { i += 2; while (i < input.length && !(input[i] === "*" && input[i + 1] === "/")) i++; i++; } else out += c; } return out; }
export async function readConfig(deps?: Deps, ctx?: Ctx): Promise<GitSyncConfig> { const dir = dirOf(deps); try { const raw = JSON.parse(stripJsonComments(await fs.readFile(path.join(dir, "git-sync.jsonc"), "utf8"))) as GitSyncConfig; const extras = (raw.extraPaths ?? []).filter(validExtra); if (extras.length !== (raw.extraPaths ?? []).length) warnOnce(ctx, "git-sync: unsafe extraPaths were ignored", deps, `${dir}|extras`); return { ...raw, extraPaths: extras }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return {}; warnOnce(ctx, "git-sync: invalid git-sync.jsonc; using defaults", deps, `${dir}|invalid`); return {}; } }
function allowRules(entry: string) { const segments = entry.replace(/\/+$/, "").split("/").filter(Boolean); const rules: string[] = []; let prefix = ""; for (let i = 0; i < segments.length; i++) { prefix = prefix ? `${prefix}/${segments[i]}` : segments[i]!; if (i < segments.length - 1) rules.push(`!${prefix}/`); else rules.push(`!${prefix}`, `!${prefix}/`, `!${prefix}/**`); } return rules; }
export async function ensureIgnoreRules(dir = dirOf(), config: GitSyncConfig = {}) { const file = path.join(dir, ".gitignore"); let existing = ""; try { existing = await fs.readFile(file, "utf8"); } catch {} const paths = [...DEFAULT_PATHS, ...(config.extraPaths ?? []).filter(validExtra)]; const lines = [START, "*", ...paths.flatMap(allowRules), "# hard denylist — re-ignored even inside allowed dirs", ...IGNORE_DENY, END]; const block = lines.join("\n"); const re = new RegExp(`${escapeRegExp(START)}[\\s\\S]*?${escapeRegExp(END)}\\n?`); await fs.mkdir(dir, { recursive: true }); await fs.writeFile(file, (re.test(existing) ? existing.replace(re, "") : existing.replace(/\s*$/, "\n")) + block + "\n"); }
export async function ensureInfoExclude(dir = dirOf()) { const file = path.join(dir, ".git", "info", "exclude"); await fs.mkdir(path.dirname(file), { recursive: true }); let current = ""; try { current = await fs.readFile(file, "utf8"); } catch {} const missing = IGNORE_DENY.filter(rule => !current.split("\n").includes(rule)); if (missing.length) await fs.writeFile(file, current.replace(/\s*$/, "\n") + missing.join("\n") + "\n"); }
function escapeRegExp(text: string) { return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
async function prepareCommit(deps?: Deps, ctx?: Ctx) { const config = await readConfig(deps, ctx); await ensureIgnoreRules(dirOf(deps), config); await ensureInfoExclude(dirOf(deps)); return config; }
export async function stagedSecretFiles(dir = dirOf()) { const { stdout } = await git(["diff", "--cached", "--name-only", "-z"], dir); return stdout.split("\0").filter(Boolean).filter(isDenied); }
export async function trackedSecretFiles(dir = dirOf()) { try { const { stdout } = await git(["ls-files", "-z"], dir); return stdout.split("\0").filter(Boolean).filter(isDenied); } catch { return []; } }
export async function commitLocalChanges(deps?: Deps, commitMessage?: string, ctx?: Ctx) { const dir = dirOf(deps); await prepareCommit(deps, ctx); const status = (await git(["status", "--porcelain"], dir)).stdout.trim(); if (!status) return false; await git(["add", "-A"], dir); const bad = await stagedSecretFiles(dir); if (bad.length) { await git(["reset"], dir); throw new Error(`REFUSED to commit sensitive paths: ${bad.join(", ")}. Remove with git rm --cached <file>.`); } const config = await readConfig(deps, ctx); const suffix = config.includeHostname === false ? "" : ` from ${os.hostname()}`; await git(["commit", "-m", commitMessage ?? `pi config: auto-sync${suffix}`], dir); return true; }
async function hasDotGit(dir: string) { try { await fs.access(path.join(dir, ".git")); return true; } catch { return false; } }
async function hasCommits(dir: string) { try { await git(["rev-parse", "HEAD"], dir); return true; } catch { return false; } }
async function isSyncableRepo(dir = dirOf()) { if (!(await hasDotGit(dir))) return false; try { const { stdout } = await git(["remote"], dir); return stdout.split("\n").includes("origin"); } catch { return false; } }
async function upstreamRef(dir: string) { try { return (await git(["rev-parse", "--abbrev-ref", "@{u}"], dir)).stdout.trim(); } catch { return undefined; } }
async function counts(upstream: string, dir: string) { const { stdout } = await git(["rev-list", "--left-right", "--count", `${upstream}...HEAD`], dir); const [behind = "0", ahead = "0"] = stdout.trim().split(/\s+/); return { behind: Number(behind), ahead: Number(ahead) }; }
async function fetchOrigin(dir: string) { try { await git(["fetch", "origin"], dir); return true; } catch { return false; } }
async function integrate(upstream: string, dir: string) { try { await git(["merge", "--ff-only", upstream], dir); return true; } catch {} try { await git(["rebase", upstream], dir); return true; } catch { try { await git(["rebase", "--abort"], dir); } catch {} return false; } }
async function push(first: boolean, dir: string) { try { await git(first ? ["push", "-u", "origin", "HEAD"] : ["push"], dir, 15_000); return true; } catch { return false; } }
async function bestEffortPush(deps?: Deps) { const dir = dirOf(deps); const upstream = await upstreamRef(dir); if (!upstream) return push(true, dir); const { ahead, behind } = await counts(upstream, dir); return ahead > 0 && behind === 0 ? push(false, dir) : false; }
export async function runSync(ctx: Ctx | undefined, options: { auto: boolean; push: boolean; skipPull?: boolean }, deps?: Deps) { const dir = dirOf(deps); if (!(await isSyncableRepo(dir))) { if (!options.auto) notify(ctx, `git-sync: no git repo with an 'origin' remote in ${dir}. Run /gitsync init.`, "warning", deps); return; } if (ctx?.hasUI) ctx.ui.setStatus(STATUS_KEY, "syncing"); try { await prepareCommit(deps, ctx); const tracked = await trackedSecretFiles(dir); if (tracked.length) notify(ctx, `git-sync: tracked sensitive files: ${tracked.join(", ")}. Remove with git rm --cached <file>.`, "warning", deps); const changed: string[] = []; if (await commitLocalChanges(deps, undefined, ctx)) changed.push("committed local changes"); if (!options.skipPull) { if (!(await fetchOrigin(dir))) { if (!options.auto) notify(ctx, "git-sync: fetch failed; skipped pull/push.", "warning", deps); return; } const upstream = await upstreamRef(dir); if (upstream && (await counts(upstream, dir)).behind > 0) { if (!(await integrate(upstream, dir))) throw new Error(`local and remote diverged with conflicts; rebase aborted in ${dir}`); changed.push("pulled updates"); } } if (options.push) { const upstream = await upstreamRef(dir); if (!upstream || (await counts(upstream, dir)).ahead > 0) { if (await push(!upstream, dir)) changed.push("pushed"); } } if (changed.some(x => x.startsWith("pulled"))) notify(ctx, `git-sync: ${changed.join(", ")}. Run /reload to apply pulled config.`, "info", deps); else if (!options.auto) notify(ctx, changed.length ? `git-sync: ${changed.join(", ")}.` : "git-sync: already up to date.", "info", deps); } finally { if (ctx?.hasUI) ctx.ui.setStatus(STATUS_KEY, undefined); } }

export function parseRepoReference(input: string, fallbackOwner: string) { const raw = input.trim().replace(/\.git$/i, ""); if (!raw) return undefined; const ssh = raw.match(/^git@github\.com:([^/\s]+)\/([^/\s]+)$/i); if (ssh) return { owner: ssh[1]!, name: ssh[2]! }; try { const url = new URL(raw); if (["github.com", "www.github.com"].includes(url.hostname) && url.pathname.split("/").filter(Boolean).length === 2) { const [owner, name] = url.pathname.split("/").filter(Boolean); return { owner: owner!, name: name!.replace(/\.git$/i, "") }; } } catch {} const bits = raw.split("/").filter(Boolean); if (bits.length === 1) return { owner: fallbackOwner, name: bits[0]! }; if (bits.length === 2 && !raw.includes(":")) return { owner: bits[0]!, name: bits[1]! }; return undefined; }
function remoteFromArg(arg: string, fallback: string) { if (/^(https?|ssh):\/\//.test(arg) || /^git@/.test(arg) || arg.startsWith("/") || arg.startsWith(".")) return arg; const ref = parseRepoReference(arg, fallback); return ref ? `https://github.com/${ref.owner}/${ref.name}.git` : undefined; }
const defaultGh: GhClient = { async available() { try { await exec("gh", ["auth", "status"], { timeout: 5000 }); return true; } catch { return false; } }, async currentUser() { return (await exec("gh", ["api", "user", "--jq", ".login"])).stdout.trim(); }, async repoExists(id) { try { await exec("gh", ["repo", "view", id, "--json", "name"]); return true; } catch { return false; } }, async isPrivate(id) { try { const { stdout } = await exec("gh", ["repo", "view", id, "--json", "isPrivate"]); return (JSON.parse(stdout) as { isPrivate: boolean }).isPrivate; } catch { return undefined; } }, async createPrivateRepo(id) { await exec("gh", ["repo", "create", id, "--private"], { timeout: 15_000 }); }, remoteUrl(id) { return `https://github.com/${id}.git`; } };
async function addRemote(url: string, dir: string) { await git(["remote", "add", "origin", url], dir); }
async function hasOrigin(dir: string) { return isSyncableRepo(dir); }
async function initRepo(dir: string) { if (!(await hasDotGit(dir))) await git(["init", "-b", "main"], dir); }
async function warnPublic(ctx: Ctx | undefined, deps?: Deps) { const dir = dirOf(deps), config = await readConfig(deps, ctx); if (config.warnOnPublicRemote === false) return; const gh = deps?.gh ?? defaultGh; if (!(await gh.available())) return; try { const remote = (await git(["remote", "get-url", "origin"], dir)).stdout.trim(); const ref = parseRepoReference(remote, ""); if (ref && await gh.isPrivate(`${ref.owner}/${ref.name}`) === false) notify(ctx, "git-sync: remote is PUBLIC — pi-git-sync never syncs secrets, but review what you allowlist; silence with warnOnPublicRemote: false in git-sync.jsonc", "warning", deps); } catch {} }
export async function runInit(arg: string, ctx?: Ctx, deps?: Deps) { const dir = dirOf(deps); await fs.mkdir(dir, { recursive: true }); if (await hasOrigin(dir)) throw new Error("already initialized; use /gitsync sync"); const config = await readConfig(deps, ctx); await ensureIgnoreRules(dir, config); await initRepo(dir); await ensureInfoExclude(dir); const tracked = await trackedSecretFiles(dir); if (tracked.length) throw new Error(`tracked sensitive files: ${tracked.join(", ")}. Remove with git rm --cached <file>.`); await commitLocalChanges(deps, "pi config: initial sync setup", ctx); let remote = remoteFromArg(arg, ""); if (!remote) { const gh = deps?.gh ?? defaultGh; if (!(await gh.available())) { notify(ctx, "git-sync: initial commit created. Create a private repo, then run /gitsync init <url>.", "warning", deps); return; } const owner = await gh.currentUser(); const ref = parseRepoReference(arg || "pi-agent-config", owner); if (!ref) throw new Error(`invalid repository reference: ${arg}`); const id = `${ref.owner}/${ref.name}`; if (await gh.repoExists(id)) throw new Error("repository already exists; use /gitsync link instead"); await gh.createPrivateRepo(id); remote = gh.remoteUrl(id); } await addRemote(remote, dir); if (!(await push(true, dir))) throw new Error("initial push failed"); await warnPublic(ctx, deps); notify(ctx, "git-sync: initialized and pushed private config repo.", "info", deps); }
async function defaultBranch(dir: string) { try { const { stdout } = await git(["ls-remote", "--symref", "origin", "HEAD"], dir); const found = stdout.match(/ref: refs\/heads\/([^\s]+)\s+HEAD/); return found?.[1] ?? "main"; } catch { return "main"; } }
async function backupConflicts(dir: string, branch: string) { const { stdout } = await git(["ls-tree", "-r", "--name-only", "-z", `origin/${branch}`], dir); const backups: string[] = []; for (const relative of stdout.split("\0").filter(Boolean)) { const target = path.join(dir, relative); try { await fs.lstat(target); } catch { continue; } const local = await fs.readFile(target).catch(() => undefined); const remote = await gitRaw(["show", `origin/${branch}:${relative}`], dir).then(x => x.stdout).catch(() => undefined); if (local && remote && !local.equals(remote)) { await fs.rename(target, `${target}.local-backup`); backups.push(relative); } } return backups; }
export async function runLink(arg: string, ctx?: Ctx, deps?: Deps) { const dir = dirOf(deps); if (await hasOrigin(dir)) throw new Error("already linked; use /gitsync sync"); const gh = deps?.gh ?? defaultGh; let remote = remoteFromArg(arg, ""); if (!remote) { if (!(await gh.available())) { notify(ctx, "git-sync: provide a repo URL, or install and authenticate gh.", "warning", deps); return; } const owner = await gh.currentUser(); for (const name of LIKELY_SYNC_REPO_NAMES) if (await gh.repoExists(`${owner}/${name}`)) { remote = gh.remoteUrl(`${owner}/${name}`); break; } if (!remote) throw new Error("no sync repository found; provide its URL"); } await fs.mkdir(dir, { recursive: true }); if ((await hasDotGit(dir)) && (await hasCommits(dir))) throw new Error(`existing git history in ${dir} has no 'origin' remote; push or back it up (or remove ${path.join(dir, ".git")}) before linking`); await initRepo(dir); await ensureIgnoreRules(dir, await readConfig(deps, ctx)); await ensureInfoExclude(dir); await addRemote(remote, dir); await git(["fetch", "origin"], dir); const branch = await defaultBranch(dir); const backups = await backupConflicts(dir, branch); try { await git(["checkout", "-B", branch, `origin/${branch}`], dir); } catch (error) { const output = message(error); const refused = output.match(/would be overwritten by checkout:\n([\s\S]*?)Please move or remove/)?.[1]?.split("\n").map(line => line.trim()).filter(Boolean) ?? []; for (const relative of refused) { if (isDenied(relative)) continue; const target = path.join(dir, relative); try { await fs.rename(target, `${target}.local-backup`); backups.push(relative); } catch {} } if (refused.length) { try { await git(["checkout", "-B", branch, `origin/${branch}`], dir); } catch (retry) { throw new Error(`${message(retry)}\nResolve manually in ${dir}`); } } else throw new Error(`${output}\nResolve manually in ${dir}`); } const tracked = await trackedSecretFiles(dir); if (tracked.length) notify(ctx, `git-sync: remote tracks sensitive files: ${tracked.join(", ")}. Remove with git rm --cached <file>.`, "warning", deps); await warnPublic(ctx, deps); notify(ctx, `git-sync: linked — run /reload to apply pulled config.${backups.length ? ` Backed up: ${backups.join(", ")}.` : ""}`, "info", deps); }
async function showStatus(ctx: ExtensionCommandContext, deps?: Deps) { const dir = dirOf(deps); if (!(await isSyncableRepo(dir))) { notify(ctx, `git-sync: ${dir} is not initialized. Run /gitsync init.`, "warning", deps); return; } const branch = (await git(["rev-parse", "--abbrev-ref", "HEAD"], dir)).stdout.trim(); const dirty = (await git(["status", "--porcelain"], dir)).stdout.trim(); const bad = await trackedSecretFiles(dir); notify(ctx, `repo: ${dir}\nbranch: ${branch}\nuncommitted changes: ${dirty ? "yes" : "none"}${bad.length ? `\nWARNING tracked sensitive files: ${bad.join(", ")}` : ""}`, bad.length ? "warning" : "info", deps); await warnPublic(ctx, deps); }
async function readState(dir: string) { try { return JSON.parse(await fs.readFile(statePath(dir), "utf8")) as { lastAutoSyncAt?: string }; } catch { return {}; } }
async function writeState(state: { lastAutoSyncAt: string }, dir = dirOf()) { await fs.mkdir(stateDir(dir), { recursive: true }); await fs.writeFile(statePath(dir), JSON.stringify(state)); }
export async function shouldAutoSync(deps?: Deps) { const dir = dirOf(deps); if (isSubagentChild() || !(await isSyncableRepo(dir))) return false; const state = await readState(dir); if (!state.lastAutoSyncAt) return true; const config = await readConfig(deps); return Date.now() - Date.parse(state.lastAutoSyncAt) >= (config.autoSyncIntervalMinutes ?? 5) * 60_000; }
export async function withLock<T>(ctx: Ctx | undefined, fn: () => Promise<T>, deps?: Deps): Promise<T | undefined> { const dir = dirOf(deps); await fs.mkdir(stateDir(dir), { recursive: true }); try { const handle = await fs.open(lockPath(dir), "wx"); await handle.writeFile(JSON.stringify({ pid: process.pid, startedAt: new Date().toISOString() })); await handle.close(); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; try { const lock = JSON.parse(await fs.readFile(lockPath(dir), "utf8")) as { pid: number; startedAt: string }; if (Number.isInteger(lock.pid) && lock.pid > 0) { process.kill(lock.pid, 0); if (Date.now() - Date.parse(lock.startedAt) < 600_000) return undefined; } } catch {} await fs.rm(lockPath(dir), { force: true }); return withLock(ctx, fn, deps); } try { return await fn(); } finally { await fs.rm(lockPath(dir), { force: true }); } }
